name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        required: true

env:
  IMAGE_NAME: ghcr.io/ksm2/bootcamp-slack-app

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set author in Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Change version
        run: |
          mv deno.json deno.json.bak
          jq '.version = "${{ github.event.inputs.version }}"' deno.json.bak > deno.json

      - name: Commit version change
        run: |
          git add deno.json
          git commit -m "${{ github.event.inputs.version }}"
          git tag "v${{ github.event.inputs.version }}"

      - name: Tag Docker image
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:v${{ github.event.inputs.version }}
          docker push ${{ env.IMAGE_NAME }}:v${{ github.event.inputs.version }}

      - name: Push release commit
        run: |
          git push --tags origin ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          draft: true
